#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${M2W_VLA_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

# Real-world M2W put-mango training.
# Thin wrapper over scripts/train_subtask_m2w_deepspeed.sh. It reuses the
# Robotwin W2 / implicit-CoT path, but switches to the single real-world
# put_mango dataset with a 16-step action chunk; wrist/V-JEPA clips are temporally sampled.

export WANDB_MODE=${WANDB_MODE:-offline}
export WANDB_PROJECT=${WANDB_PROJECT:-w2-vla}
export WANDB_ENTITY=${WANDB_ENTITY:-}

CONFIG=${CONFIG:-${REPO_ROOT}/starVLA/config/training/subtask_m2w_robotwin_w2.yaml}

DATA_ROOT_DIR=${DATA_ROOT_DIR:-${REPO_ROOT}/playground/Datasets/W2-VLA-Training-Data/real_world}
DATA_MIX=${DATA_MIX:-realworld_put_mango_stride2}
DATASET_PY=${DATASET_PY:-subtask_m2w_robotwin_w2_datasets}
SUBTASK_LABEL_DIR=${SUBTASK_LABEL_DIR:-${REPO_ROOT}/playground/Datasets/W2-VLA-CoT/real_world}
COT_PROMPT_VERSION=${COT_PROMPT_VERSION:-realworld_put_mango_tri_v1}
COT_PROMPT=${COT_PROMPT:-$'Your task is: {instruction}\n\nUsing the current high camera, left wrist camera, and right wrist camera images, identify the current robot manipulation step.\n\nOutput exactly:\nSubtask: ...\nReasoning: ...\nWrist: left=...; right=...\n\nDo not add extra text.'}
PREFER_LABEL_INSTRUCTION=${PREFER_LABEL_INSTRUCTION:-true}

ACTION_HORIZON=${ACTION_HORIZON:-16}
FUTURE_ACTION_WINDOW_SIZE=${FUTURE_ACTION_WINDOW_SIZE:-15}
PAST_ACTION_WINDOW_SIZE=${PAST_ACTION_WINDOW_SIZE:-0}
ACTION_DIM=${ACTION_DIM:-14}
STATE_DIM=${STATE_DIM:-14}
ACTION_TYPE=${ACTION_TYPE:-abs_qpos}
ACTION_MODE=${ACTION_MODE:-abs}
INCLUDE_STATE=${INCLUDE_STATE:-false}

NUM_PROCESSES=${NUM_PROCESSES:-4}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-4}
GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-1}
MAX_TRAIN_STEPS=${MAX_TRAIN_STEPS:-100000}
NUM_WARMUP_STEPS=${NUM_WARMUP_STEPS:-5000}
SAVE_INTERVAL=${SAVE_INTERVAL:-5000}
LOGGING_FREQUENCY=${LOGGING_FREQUENCY:-50}
EVAL_INTERVAL=${EVAL_INTERVAL:-1000}
NUM_WORKERS=${NUM_WORKERS:-3}
PREFETCH_FACTOR=${PREFETCH_FACTOR:-2}
RUN_ROOT_DIR=${RUN_ROOT_DIR:-${REPO_ROOT}/results/Checkpoints}
RUN_ID=${RUN_ID:-realworld_put_mango_stride2_h16_implicit_cot_w2}

COT_REASONING_MODE=${COT_REASONING_MODE:-implicit_query}
LATENT_COT_NUM_QUERIES=${LATENT_COT_NUM_QUERIES:-16}
QWEN_ACTION_CONTEXT_MODE=${QWEN_ACTION_CONTEXT_MODE:-exclude_cot_prompt}
LAMBDA_COT=${LAMBDA_COT:-0.1}
GENERATE_COT_AT_INFERENCE=${GENERATE_COT_AT_INFERENCE:-false}

USE_JEPA_LOSS=${USE_JEPA_LOSS:-true}
LAMBDA_JEPA=${LAMBDA_JEPA:-0.2}
NUM_WRIST_VIEWS=${NUM_WRIST_VIEWS:-2}
WRIST_HISTORY_FRAMES=${WRIST_HISTORY_FRAMES:-8}
LOAD_WRIST_FUTURE_VIEWS=${LOAD_WRIST_FUTURE_VIEWS:-true}
FUTURE_WRIST_K=${FUTURE_WRIST_K:-16}
FUTURE_WRIST_SMALL_GAP=${FUTURE_WRIST_SMALL_GAP:-2}
VLM_INCLUDE_WRIST_VIEW=${VLM_INCLUDE_WRIST_VIEW:-true}
VIDEO_BACKEND=${VIDEO_BACKEND:-torchvision_av}

TRAIN_QWEN_VL=${TRAIN_QWEN_VL:-true}
FIND_UNUSED_PARAMETERS=${FIND_UNUSED_PARAMETERS:-false}
REPEATED_DIFFUSION_STEPS=${REPEATED_DIFFUSION_STEPS:-8}
DIT_DROPOUT=${DIT_DROPOUT:-0.2}

export DATA_ROOT_DIR DATA_MIX DATASET_PY SUBTASK_LABEL_DIR COT_PROMPT_VERSION COT_PROMPT PREFER_LABEL_INSTRUCTION
export ACTION_HORIZON FUTURE_ACTION_WINDOW_SIZE PAST_ACTION_WINDOW_SIZE ACTION_DIM STATE_DIM ACTION_TYPE ACTION_MODE INCLUDE_STATE
export NUM_PROCESSES PER_DEVICE_BATCH_SIZE GRADIENT_ACCUMULATION_STEPS MAX_TRAIN_STEPS NUM_WARMUP_STEPS SAVE_INTERVAL LOGGING_FREQUENCY EVAL_INTERVAL NUM_WORKERS PREFETCH_FACTOR RUN_ROOT_DIR RUN_ID
export COT_REASONING_MODE LATENT_COT_NUM_QUERIES QWEN_ACTION_CONTEXT_MODE LAMBDA_COT GENERATE_COT_AT_INFERENCE
export USE_JEPA_LOSS LAMBDA_JEPA NUM_WRIST_VIEWS WRIST_HISTORY_FRAMES LOAD_WRIST_FUTURE_VIEWS FUTURE_WRIST_K FUTURE_WRIST_SMALL_GAP VLM_INCLUDE_WRIST_VIEW VIDEO_BACKEND
export TRAIN_QWEN_VL FIND_UNUSED_PARAMETERS REPEATED_DIFFUSION_STEPS DIT_DROPOUT

# The real-world release uses the same LeRobot modality layout as RoboTwin, but
# the downloaded folder may not include meta/modality.json. GR00T requires it.
MODALITY_JSON="${DATA_ROOT_DIR}/put_mango/meta/modality.json"
if [[ ! -f "${MODALITY_JSON}" ]]; then
  echo "[RealWorld M2W] installing modality metadata: ${MODALITY_JSON}"
  cp "${REPO_ROOT}/examples/Robotwin/train_files/modality.json" "${MODALITY_JSON}"
fi

bash "${REPO_ROOT}/scripts/train_subtask_m2w_deepspeed.sh" "${CONFIG}" "$@"
